#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <libopencm3/usb/usbd.h>
#include <libopencm3/usb/cdc.h>
#include <libopencm3/stm32/desig.h>
#include "cdc.h"
#include "webusb.h"
#include "usb_conf.h"
